version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  db1:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: money-lover-operation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root