CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    category_type VARCHAR(255),
    parent_id     BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE operations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date          VARCHAR(255),
    wallet_id     BIGINT,
    category_id   BIGINT,
    operation_sum BIGINT,
    note          VARCHAR(255),
    CONSTRAINT pk_operations PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);